---
- name: Clean yum cache
  command: yum clean all
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == '7'

- name: Clean dnf cache
  command: dnf clean all
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version is version('8', '>=')

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Update all system packages
  package:
    name: '*'
    state: latest
  ignore_errors: true
...
